"""initial

Revision ID: 18db62aa53ab
Revises: 
Create Date: 2026-03-09 14:21:03.999105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '18db62aa53ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Predict_id'), table_name='Predict')
    op.drop_table('Predict')
    op.drop_index(op.f('ix_Ingredient_History_id'), table_name='Ingredient_History')
    op.drop_table('Ingredient_History')
    op.drop_table('Ingredient')
    op.drop_index(op.f('ix_Staff_id'), table_name='Staff')
    op.drop_table('Staff')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Staff',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('restaurant_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Staff_id'), 'Staff', ['id'], unique=False)
    op.create_table('Ingredient',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('stock_left', mysql.FLOAT(), nullable=True),
    sa.Column('last_update', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Ingredient_History',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('action_type', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('ingredient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('staff_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('restaurant_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_current', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['Ingredient.id'], name=op.f('Ingredient_History_ibfk_1')),
    sa.ForeignKeyConstraint(['staff_id'], ['Staff.id'], name=op.f('Ingredient_History_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Ingredient_History_id'), 'Ingredient_History', ['id'], unique=False)
    op.create_table('Predict',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ingredient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prediction_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('amount_need', mysql.FLOAT(), nullable=True),
    sa.Column('prediction_set', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('restaurant_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['Ingredient.id'], name=op.f('Predict_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Predict_id'), 'Predict', ['id'], unique=False)
    # ### end Alembic commands ###
