"""add staff username and password

Revision ID: 30d78358047d
Revises: ff941a11fcb1
Create Date: 2026-05-02 22:58:33.019321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d78358047d'
down_revision: Union[str, None] = 'ff941a11fcb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('username', sa.Text(), nullable=False))
    op.add_column('staff', sa.Column('password', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'password')
    op.drop_column('staff', 'username')
    # ### end Alembic commands ###
