"""change_new_current_to_decimal

Revision ID: 85fb2ff8f88b
Revises: 9fa399f60dec
Create Date: 2026-05-01 17:16:35.313866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '85fb2ff8f88b'
down_revision: Union[str, None] = '9fa399f60dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient_history', 'new_current',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=8, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient_history', 'new_current',
               existing_type=sa.DECIMAL(precision=8, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
