"""description of changes

Revision ID: 8fc47b284428
Revises: fbb00e105f85
Create Date: 2026-04-05 17:05:38.170042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc47b284428'
down_revision: Union[str, None] = 'fbb00e105f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predict', sa.Column('urgency_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predict', 'urgency_score')
    # ### end Alembic commands ###
