"""update predict and predict_set

Revision ID: 96f3d17ec756
Revises: a1b2c3d4e5f6
Create Date: 2026-04-02 17:58:45.504650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '96f3d17ec756'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predict', sa.Column('expected_usage', sa.DECIMAL(precision=8, scale=2), nullable=False))
    op.add_column('predict', sa.Column('upper_bound', sa.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('predict', sa.Column('lower_bound', sa.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('predict', sa.Column('daily_target_average', sa.DECIMAL(precision=8, scale=2), nullable=True))
    op.drop_column('predict', 'amount_need')
    op.add_column('predict_set', sa.Column('model', sa.Integer(), nullable=False))
    op.add_column('predict_set', sa.Column('day_ahead', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predict_set', 'day_ahead')
    op.drop_column('predict_set', 'model')
    op.add_column('predict', sa.Column('amount_need', mysql.DECIMAL(precision=8, scale=2), nullable=False))
    op.drop_column('predict', 'daily_target_average')
    op.drop_column('predict', 'lower_bound')
    op.drop_column('predict', 'upper_bound')
    op.drop_column('predict', 'expected_usage')
    # ### end Alembic commands ###
