"""update predict and predict_set

Revision ID: fbb00e105f85
Revises: 96f3d17ec756
Create Date: 2026-04-02 18:06:14.873237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fbb00e105f85'
down_revision: Union[str, None] = '96f3d17ec756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predict_set', 'prediction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predict_set', sa.Column('prediction_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
